# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Channel 2' do
	pod 'PopupDialog', ‘0.3.2’
	pod 'SwiftyJSON’, ‘2.3.2’
	pod "AsyncSwift”, ‘1.7.3’
	pod 'Eureka', '1.7'
end

target 'Channel 2Tests' do
	pod 'PopupDialog', ‘0.3.2’
	pod 'SwiftyJSON’, ‘2.3.2’
	pod "AsyncSwift”, ‘1.7.3’
	pod 'Eureka', '1.7'
end

target 'Channel 2UITests' do
	pod 'PopupDialog', ‘0.3.2’
	pod 'SwiftyJSON’, ‘2.3.2’
	pod "AsyncSwift”, ‘1.7.3’
	pod 'Eureka', '1.7'
end
