# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Channel 2' do
	pod 'SwiftyJSON’, ‘2.3.2’
	pod "AsyncSwift”, ‘1.7.3’
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
	pod 'Firebase/AdMob’
	pod 'LNRSimpleNotifications', :git => 'https://github.com/LISNR/LNRSimpleNotifications.git', :branch => 'swift2.3'
end

target 'Channel 2Tests' do
	pod 'SwiftyJSON’, ‘2.3.2’
	pod "AsyncSwift”, ‘1.7.3’
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
	pod 'Firebase/AdMob’
	pod 'LNRSimpleNotifications', :git => 'https://github.com/LISNR/LNRSimpleNotifications.git', :branch => 'swift2.3'
end

target 'Channel 2UITests' do
	pod 'SwiftyJSON’, ‘2.3.2’
	pod "AsyncSwift”, ‘1.7.3’
	pod 'Firebase/Core'
	pod 'Firebase/Messaging'
	pod 'Firebase/AdMob’
	pod 'LNRSimpleNotifications', :git => 'https://github.com/LISNR/LNRSimpleNotifications.git', :branch => 'swift2.3'
end
